# Form implementation generated from reading ui file 'ListAdd.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiForm(object):
    def __init__(self, form):
        super(UiForm, self).__init__()

        form.setObjectName("Form")
        form.resize(600, 500)

        self.pushButton = QtWidgets.QPushButton(form)
        self.listWidget = QtWidgets.QListWidget(form)
        self.lineEdit = QtWidgets.QLineEdit(form)
        self.label = QtWidgets.QLabel(form)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.verticalLayout = QtWidgets.QVBoxLayout(form)

        self.setup_ui()
        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def setup_ui(self):
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout.setObjectName("horizontalLayout")
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton.clicked.connect(self.add_item)

    def retranslateUi(self, _form):
        _translate = QtCore.QCoreApplication.translate
        _form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Favorite Programming Language:"))
        self.pushButton.setText(_translate("Form", "Add Item"))

    def add_item(self):
        self.listWidget.addItem(self.lineEdit.text())
        self.lineEdit.setText('')

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    _form = QtWidgets.QWidget()
    ui = UiForm(_form)
    # ui.setup_ui(form)
    _form.show()
    sys.exit(app.exec())
