# Form implementation generated from reading ui file 'ViewMember.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt6.QtWidgets import QTableWidgetItem


class Ui_ViewMemberDialog(object):
    def setupUi(self, ViewMemberDialog):
        ViewMemberDialog.setObjectName("ViewMemberDialog")
        ViewMemberDialog.resize(650, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(ViewMemberDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(ViewMemberDialog)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"background-color:rgb(218,218,218);\n"
"color:black\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton = QtWidgets.QPushButton(ViewMemberDialog)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(ViewMemberDialog)
        QtCore.QMetaObject.connectSlotsByName(ViewMemberDialog)

    def retranslateUi(self, ViewMemberDialog):
        _translate = QtCore.QCoreApplication.translate
        ViewMemberDialog.setWindowTitle(_translate("ViewMemberDialog", "View Members"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ViewMemberDialog", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ViewMemberDialog", "Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ViewMemberDialog", "Mobile"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ViewMemberDialog", "Email"))
        self.pushButton.setText(_translate("ViewMemberDialog", "View Members"))

        self.pushButton.clicked.connect(self.view_members)

    def view_members(self):
        try:
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="Fletter#01",
                database="library"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM tbl_addmember")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    item = QTableWidgetItem(str(data))
                    self.tableWidget.setItem(row_number, column_number, item)


        except mc.Error as e:
            print("Error: ", e.msg)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ViewMemberDialog = QtWidgets.QDialog()
    ui = Ui_ViewMemberDialog()
    ui.setupUi(ViewMemberDialog)
    ViewMemberDialog.show()
    sys.exit(app.exec())
